spring:
  datasource:
    url: jdbc:mysql://localhost:3307/mybatis
    username: root
    password: 123456
server:
  port: 8080
security:
  basic:
    enabled: true
  user:
    name: admin
    password: password
mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.wjy.model
  configuration:
    cache-enabled: true
    map-underscore-to-camel-case: true
pagehelper:
  reasonable: true
